//
//  SearchResultsShipment.h
//  
//
//  Created by Haralambos Yokos on 7/19/12.
//  Copyright (c) 2012 Zeus Framework. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface SearchResultsShipment : NSObject {
    NSString *account;
    id bookedDateTime;
    NSString *bookingNumber;
    NSString *cargoLocation;
    NSString *carrier;
    NSString *cartons;
    NSString *cBM;
    NSString *cFT;
    id clearedDateTime;
    NSString *clientId;
    id closingDateTime;
    NSString *cODAmount;
    NSString *cODFlag;
    NSString *commodity;
    id completedFlag;
    id confirmedArrivalDate;
    id confirmedDepartureDate;
    NSString *consignee;
    NSString *contactEmail;
    id contactFax;
    NSString *contactName;
    NSString *contactPhoneFax;
    NSString *conveyance;
    NSString *createdDateTime;
    NSString *customerReferenceNumber;
    NSString *customsEntryNumber;
    id cutoffDateTime;
    NSArray *data;
    NSString *dateFileOpen;
    id deliveredDateTime;
    NSString *deliveryAddress;
    id doorETADateTime;
    NSString *downstairs;
    id entryFiledDate;
    NSString *eTADateTime;
    NSString *fileId;
    NSString *fileNumber;
    NSString *fileType;
    NSString *forklift;
    NSString *forwarder;
    NSString *fORWARDERSRE;
    id goDateDateTime;
    NSString *hazardousDescription;
    NSString *houseNumber;
    NSString *inBondNumber;
    id iTDate;
    NSString *kilos;
    id lastFreeDayDateTime;
    NSString *lCLFlag;
    NSString *liftgate;
    NSString *loadingDock;
    NSString *master;
    NSString *masterId;
    NSString *masterNumber;
    NSString *module;
    NSString *no20;
    NSString *no40;
    NSString *no40HC;
    NSString *notes;
    NSString *notify;
    NSString *oblRequired;
    NSString *pickupAt;
    id pickupDateTime;
    NSString *pieces;
    NSString *pieceType;
    NSString *placeOfDelivery;
    NSString *placeOfReceipt;
    id pODate;
    id pOInputDate;
    NSString *portOfDischarge;
    NSString *portOfLoad;
    NSString *pounds;
    id readyDateTime;
    NSString *reeferTemperature;
    id requestedDeliveryDateTime;
    id returnDate;
    NSString *routingParty;
    NSString *sailDateTime;
    NSString *serviceType;
    NSString *shipmentId;
    NSString *shipper;
    NSString *siteId;
    NSString *status;
    NSString *statusCode;
    BOOL success;
    NSString *tEU;
    NSString *thirdParty;
    NSNumber *total;
    NSString *typeOfMove;
    NSString *ultimateDestination;
    NSString *uNContactNumber;
    NSString *uNFlag;
    NSString *uNNumber;
    NSString *upstairs;
    NSString *vessel;
    NSString *voyage;
}

@property (nonatomic, copy) NSString *account;
@property (nonatomic, retain) id bookedDateTime;
@property (nonatomic, copy) NSString *bookingNumber;
@property (nonatomic, copy) NSString *cargoLocation;
@property (nonatomic, copy) NSString *carrier;
@property (nonatomic, copy) NSString *cartons;
@property (nonatomic, copy) NSString *cBM;
@property (nonatomic, copy) NSString *cFT;
@property (nonatomic, retain) id clearedDateTime;
@property (nonatomic, copy) NSString *clientId;
@property (nonatomic, retain) id closingDateTime;
@property (nonatomic, copy) NSString *cODAmount;
@property (nonatomic, copy) NSString *cODFlag;
@property (nonatomic, copy) NSString *commodity;
@property (nonatomic, retain) id completedFlag;
@property (nonatomic, retain) id confirmedArrivalDate;
@property (nonatomic, retain) id confirmedDepartureDate;
@property (nonatomic, copy) NSString *consignee;
@property (nonatomic, copy) NSString *contactEmail;
@property (nonatomic, retain) id contactFax;
@property (nonatomic, copy) NSString *contactName;
@property (nonatomic, copy) NSString *contactPhoneFax;
@property (nonatomic, copy) NSString *conveyance;
@property (nonatomic, copy) NSString *createdDateTime;
@property (nonatomic, copy) NSString *customerReferenceNumber;
@property (nonatomic, copy) NSString *customsEntryNumber;
@property (nonatomic, retain) id cutoffDateTime;
@property (nonatomic, copy) NSArray *data;
@property (nonatomic, copy) NSString *dateFileOpen;
@property (nonatomic, retain) id deliveredDateTime;
@property (nonatomic, copy) NSString *deliveryAddress;
@property (nonatomic, retain) id doorETADateTime;
@property (nonatomic, copy) NSString *downstairs;
@property (nonatomic, retain) id entryFiledDate;
@property (nonatomic, copy) NSString *eTADateTime;
@property (nonatomic, copy) NSString *fileId;
@property (nonatomic, copy) NSString *fileNumber;
@property (nonatomic, copy) NSString *fileType;
@property (nonatomic, copy) NSString *forklift;
@property (nonatomic, copy) NSString *forwarder;
@property (nonatomic, copy) NSString *fORWARDERSRE;
@property (nonatomic, retain) id goDateDateTime;
@property (nonatomic, copy) NSString *hazardousDescription;
@property (nonatomic, copy) NSString *houseNumber;
@property (nonatomic, copy) NSString *inBondNumber;
@property (nonatomic, retain) id iTDate;
@property (nonatomic, copy) NSString *kilos;
@property (nonatomic, retain) id lastFreeDayDateTime;
@property (nonatomic, copy) NSString *lCLFlag;
@property (nonatomic, copy) NSString *liftgate;
@property (nonatomic, copy) NSString *loadingDock;
@property (nonatomic, copy) NSString *master;
@property (nonatomic, copy) NSString *masterId;
@property (nonatomic, copy) NSString *masterNumber;
@property (nonatomic, copy) NSString *module;
@property (nonatomic, copy) NSString *no20;
@property (nonatomic, copy) NSString *no40;
@property (nonatomic, copy) NSString *no40HC;
@property (nonatomic, copy) NSString *notes;
@property (nonatomic, copy) NSString *notify;
@property (nonatomic, copy) NSString *oblRequired;
@property (nonatomic, copy) NSString *pickupAt;
@property (nonatomic, retain) id pickupDateTime;
@property (nonatomic, copy) NSString *pieces;
@property (nonatomic, copy) NSString *pieceType;
@property (nonatomic, copy) NSString *placeOfDelivery;
@property (nonatomic, copy) NSString *placeOfReceipt;
@property (nonatomic, retain) id pODate;
@property (nonatomic, retain) id pOInputDate;
@property (nonatomic, copy) NSString *portOfDischarge;
@property (nonatomic, copy) NSString *portOfLoad;
@property (nonatomic, copy) NSString *pounds;
@property (nonatomic, retain) id readyDateTime;
@property (nonatomic, copy) NSString *reeferTemperature;
@property (nonatomic, retain) id requestedDeliveryDateTime;
@property (nonatomic, retain) id returnDate;
@property (nonatomic, copy) NSString *routingParty;
@property (nonatomic, copy) NSString *sailDateTime;
@property (nonatomic, copy) NSString *serviceType;
@property (nonatomic, copy) NSString *shipmentId;
@property (nonatomic, copy) NSString *shipper;
@property (nonatomic, copy) NSString *siteId;
@property (nonatomic, copy) NSString *status;
@property (nonatomic, copy) NSString *statusCode;
@property (nonatomic, assign) BOOL success;
@property (nonatomic, copy) NSString *tEU;
@property (nonatomic, copy) NSString *thirdParty;
@property (nonatomic, copy) NSNumber *total;
@property (nonatomic, copy) NSString *typeOfMove;
@property (nonatomic, copy) NSString *ultimateDestination;
@property (nonatomic, copy) NSString *uNContactNumber;
@property (nonatomic, copy) NSString *uNFlag;
@property (nonatomic, copy) NSString *uNNumber;
@property (nonatomic, copy) NSString *upstairs;
@property (nonatomic, copy) NSString *vessel;
@property (nonatomic, copy) NSString *voyage;

+ (SearchResultsShipment *)instanceFromDictionary:(NSDictionary *)aDictionary;
- (void)setAttributesFromDictionary:(NSDictionary *)aDictionary;

@end
